### ISSUE TITLE
Refactoring: namespace

### ISSUE THREAD

**Issue by mecab** [greymd/ttcopy#12]
Most of the functions and variables in `wpb.sh` should not be called by user.
How about adding prefix them to tell them as "private" and used in `wpb`.

Proposals
----------
 - public variables: `$WPB_ID`
 - private variables: `$_WPB_PIPE`
 - public functions: `wpbcopy()`    
(No prefix. Also need to consider #11 )
 - private functions: `__wpb::spin()`

They are referred from `zplug`.

**Comment by greymd** [comment]
I second it!
