### ISSUE TITLE
Release v1.0 (or 0.9 or something)

### ISSUE THREAD

**Issue by mecab** [greymd/ttcopy#15]
I think it already has enough stuff to work at least.

Let's release it now, or let's define the issues which we have to solve before the release.

**Comment by greymd** [comment]
That's the stuff.
But, I want to re-consider #17 before the first release if possible.

**Comment by greymd** [comment]
I made `develop-1.0.0` branch. After merging it, let us create a new commit for bumping version & stick git tag.
