### ISSUE TITLE
📛  Reconsider command name ( & repository name).

### ISSUE THREAD

**Issue by greymd** [greymd/ttcopy#17]
Excuse me.
Maybe I should create this issue more earlier...

I want to reconsider the name name of `wpbcopy` and `wpbpaste` and also the repository name.
They are not bad actually. It expresses the role of those commands well.

However, there are some concerns for me

* Difficult to type (continuous "w" and "p" keys are troublesome).
* Lazy to say (especially in Japanese: だぶりゅーぴーびーこぴー?).
  + Not catchy phrase.

How do you think about the current name of repository and command?
Once It is released, it will be very difficult to change and I want to have an opportunity to reconsider it.
if you have any ideas or candidates, let's share it here.
Off course, keeping current name is ok. it is not bad choice.

とても今更なんですが、そもそも名前どうなのってのを考えたく。。
今の名前も悪くはないんですが。

* * *
1. `wcopy` & `wpaste`
First of all, I wondered we can use `wcopy` and `wpaste` ( Web + Copy ).
But unfortunately, the same command is already existing( [wcopy](http://linuxcommand.org/man_pages/wcopy1.html) ).

2. `rcopy` & `rpaste`
"r" means "Remote".
Also it's existing [rcopy](https://linux.die.net/man/1/rcopy).

3. `icopy` & `ipaste`
"i" means "Internet".
It does not exist, but it sounds like Apple's something...

**Comment by mecab** [comment]
icopy / ipaste seems good (yeah, it sounds like Apple, indeed...)

or just simply webcopy and webpaste? It's a bit long, but I guess type-friendly.

確かに発音しにくいなーとは思ってたw

**Comment by greymd** [comment]
I prefer web{copy,paste} to wpb{copy,paste}. simple is good.
yeah, I want more shorter one if possible.

**Comment by greymd** [comment]
hmm... 🐱 

```
$ echo {a..z}{a..z}{copy,paste} | xargs -n 2
aacopy aapaste
abcopy abpaste
accopy acpaste
adcopy adpaste
aecopy aepaste
afcopy afpaste
agcopy agpaste
ahcopy ahpaste
aicopy aipaste
ajcopy ajpaste
...
```

**Comment by greymd** [comment]
"glcopy", "glpaste"
gl means "Global"

**Comment by mecab** [comment]
How about `ttcopy`.

It's more for typing than meaning..., but maybe stands for "Transfer To Copy/Paste".

**Comment by greymd** [comment]
I have one more idea.
`macopy` & `mapaste`
(Massive Copy/Paste)

"macopy" sounds like "まこぴー" which means キュアソード who is one of the best heroine in Precure.

**Comment by greymd** [comment]
I think, `ttcopy` can be "Trans Terminal Copy/Paste".
It expresses its functions very well....

**Comment by greymd** [comment]
TTCP

**Comment by greymd** [comment]
I will adopt following re-branding.
* `wpbcopy` -> `ttcopy`
* `wpbpaste` -> `ttpaste`
* `wpb` -> `ttcp`
