### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by mecab** [greymd/ttcopy#20]
Cool stuff like

```
  _____   _____    ___     ___      ___  __   __ 
 |_   _| |_   _|  / __|   / _ \    | _ \ \ \ / / 
   | |     | |   | (__   | (_) |   |  _/  \ V /  
  _|_|_   _|_|_   \___|   \___/   _|_|_   _|_|_  
_|"""""|_|"""""|_|"""""|_|"""""|_| """ |_| """ | 
"`-0-0-'"`-0-0-'"`-0-0-'"`-0-0-'"`-0-0-'"`-0-0-' 
```

**Comment by greymd** [comment]
```
 _____ _____ ____ ___  ______   __
|_   _|_   _/ ___/ _ \|  _ \ \ / /
  | |   | || |  | | | | |_) \ V /
  | |   | || |__| |_| |  __/ | |
  |_|   |_| \____\___/|_|    |_|
```

**Comment by mecab** [comment]
![ttcopy_logo](https://cloud.githubusercontent.com/assets/1580772/22251875/ae482b1a-e28f-11e6-86d1-73ee75b27bde.png)

**Comment by greymd** [comment]
![logo_gre](https://cloud.githubusercontent.com/assets/3874767/22277857/3ab4848c-e302-11e6-9257-c6d851a75649.png)

Given by http://www.ishotihadus.com/mahopregreeks.php

**Comment by greymd** [comment]
なんかもう色々だしてピンと着たのでいい気がしてきた

**Comment by greymd** [comment]
フォトショで適当に筆記体で書いてみるてすと。ぽい。

![1](https://cloud.githubusercontent.com/assets/3874767/22427610/344521b2-e747-11e6-80a9-3882ab0f7e4d.png)

**Comment by greymd** [comment]
like 3D
![2](https://cloud.githubusercontent.com/assets/3874767/22427643/535367da-e747-11e6-8d65-b0177335820e.png)

**Comment by greymd** [comment]
painted by [PaintsChainer](http://paintschainer.preferred.tech/). somehow, not bad lol.
![v1syr4xd45nvjhtu2d9g97m8pe6ihi5h_0](https://cloud.githubusercontent.com/assets/3874767/22427935/6cf5eb44-e748-11e6-93d0-04deb5ab3295.jpg)

**Comment by greymd** [comment]
TTの部分を重ねてアンテナっぽく見せる手法に気づいた。しかし駄作。
![3](https://cloud.githubusercontent.com/assets/3874767/22428946/4268cdac-e74c-11e6-8892-58938c7e61a2.png)

**Comment by mecab** [comment]
最後の、すごく惜しいというかもう少しで何かきそうな可能性をめっちゃ感じる...!

**Comment by mecab** [comment]
Fixed by #26
