### ISSUE TITLE
Sorting out exit status.

### ISSUE THREAD

**Issue by greymd** [greymd/ttcopy#25]
My suggestion about the rule related to the exit status.
How about follow the following rules AS MUCH AS POSSIBLE.

* `exit` command should be declared in the executable command files (in our case, `ttcopy.sh` or `ttpaste.sh`).
* Let's follow the way of numbering given by general command (like `sed`, `grep`).
* For our original purpose, let's avoid to use 1 - 2, 126 - 165, and 255.
FYI: http://tldp.org/LDP/abs/html/exitcodes.html

### For commands (`ttcopy` and `ttpaste`)

| Description                        | Exit status   | Note                                                                                    |
| -------------                      | ------------- | ------                                                                                  |
| Exit successfully                  | 0             |                                                                                         |
| Undefined or General errors        | 1             | something undefined for future use.                                                     |
| TTCP_ID/TTCP_PASSWORD is undefined | 3             |                                                                                         |
| Invalid option/argument            | 4             | same as GNU `sed`                                                                       |
| Nothing has been copied yet.       | 5             |                                                                                         |
| Failed to upload the content.      | 6             | transfer.sh might be down.                                                              |
| Failed to get the content url.     | 7             | cl1p.net might be down.                                                                 |
| `openssl` got something wrong.     | 8             | Maybe, invalid password?                                                                |
| Necessary commands are not found   | 127           | we can use it.. maybe.. http://stackoverflow.com/questions/1763156/127-return-code-from |
| Terminated by Ctl-C                | 130           | Try `$ cat` and type Ctrl-c.                                                            |

### For function (like `__ttcp::opts`, `__ttcp::is_env_ok`)

| Description                              | Exit status   | Note                                                                                                     |
| -------------                            | ------------- | ------                                                                                                   |
| success and allow to continue procedure. | 0             | `return 0`                                                                                               |
| let command exit successfully            | 254           | `return 254` i.e, `--help` and `--version` options.                                                      |
| Other is same as commands.               | N/A           | i,e, if the function supposed that the command exits with `4`, the function should exit with `return 4`. |

終了ステータスって探しても標準的なルールなかったので、あとは決めで良いのではという気がしている。

**Comment by mecab** [comment]
One idea is grouping related issues. So how about moving `Failed to upload the content` and `Failed to get the content url` from `6` and `7` to `16` and `17`, which indicates remote issue.

This might be helpful if this command add any remote dependent services in future.

**Comment by greymd** [comment]
yeah, that's a good idea.

**Comment by greymd** [comment]
Fix

### For commands (`ttcopy` and `ttpaste`)

| Description                        | Exit status   | Note                                                                                    |
| -------------                      | ------------- | ------                                                                                  |
| Exit successfully                  | 0             |                                                                                         |
| Undefined or General errors        | 1             | something undefined for future use.                                                     |
| TTCP_ID/TTCP_PASSWORD is undefined | 3             |                                                                                         |
| Invalid option/argument            | 4             | same as GNU `sed`                                                                       |
| Nothing has been copied yet.       | 5             |                                                                                         |
| Failed to upload the content.      | 16             | transfer.sh might be down.                                                              |
| Failed to get the content url.     | 17             | cl1p.net might be down.                                                                 |
| `openssl` got something wrong.     | 8             | Maybe, invalid password?                                                                |
| Necessary commands are not found   | 127           | we can use it.. maybe.. http://stackoverflow.com/questions/1763156/127-return-code-from |
| Terminated by Ctl-C                | 130           | Try `$ cat` and type Ctrl-c.                                                            |

### For function (like `__ttcp::opts`, `__ttcp::is_env_ok`)

| Description                              | Exit status   | Note                                                                                                     |
| -------------                            | ------------- | ------                                                                                                   |
| success and allow to continue procedure. | 0             | `return 0`                                                                                               |
| let command exit successfully            | 254           | `return 254` i.e, `--help` and `--version` options.                                                      |
| Other is same as commands.               | N/A           | i,e, if the function supposed that the command exits with `4`, the function should exit with `return 4`. |

**Comment by mecab** [comment]
Copied the table to wiki: https://github.com/greymd/ttcopy/wiki/Specs

**Comment by greymd** [comment]
Hoenstly, I am not familiar with Github's Wiki...
