### ISSUE TITLE
Proxy connection support

### ISSUE THREAD

**Issue by greymd** [greymd/ttcopy#27]
There are three ways.

### 1. let user set `http_proxy` or`https_proxy` environment variables.
This is same as `wget` command.

```sh
$ export http_proxy="http://proxy.com:port/"
$ echo aaa | ttcopy # => connecting through the proxy server.
```

### 2. Support `-x` option
This is same as `curl` command.

```sh
$ echo aaa | ttcopy -x http://proxy.com:port/
```

### 3. Same as 1, but set original variable `TTCP_PROXY`.

Personally, I prefer 3.
* The problems of 1 is, the configuration can conflict with wget.
  * In addition, it is required to detect whether the connection is  http or https. it's lazy.
* In the future, both `wget` and `curl` maybe used in order to be compatible with POSIX. The configuration for only either is better to be avoided.

**Comment by mecab** [comment]
I'm for to 3.

**Comment by mecab** [comment]
If anyone wants to implement, it's very welcome.
