### ISSUE TITLE
🤐 gzip compression

### ISSUE THREAD

**Issue by greymd** [greymd/ttcopy#28]
`gzip` command is not in the POSIX.
But I want to support it. Especially, when the delivering data is plain text, large mount of network cost can be reduced.
Let's save energy in order to save the Earth 🌏 🌍 🌎  
We can save the world.
Love & Peace.

* For `ttcopy`: copress -> encryption -> upload

```sh
... cat | gzip | openssl aes-256-cbc -e -pass pass:$TTCP_PASSWORD ...
```

* For `ttpaste`: download -> decryption -> uncompress
```sh
... cat "$TTCP_LASTPASTE_PATH" | openssl aes-256-cbc -d -pass pass:$TTCP_PASSWORD | gzip -d
```

Attention:
When we finished to implement this feature, I think **MAJOR** version should be incremented.
Because, this feature will lost the downward compatibility (old version `ttpaste` cannot download the data from new version `ttcopy`.)

**Comment by mecab** [comment]
Has been resolved by #30
