### ISSUE TITLE
Encrypt transfer.sh URL for cl1p.net

### ISSUE THREAD

**Issue by greymd** [greymd/ttcopy#29]
For now, `ttcopy` post the raw URL given by transfer.sh to cl1p.net.
In order to strengthen the encryption, it is worth encrypting the URL.
As you may know, cl1p.net is only handles plain text, so base64 encoding is required.

I made `develop-2.0.0` branch for #28 . I would like to resolve this issue at the same branch.

**Comment by greymd** [comment]
なんとなくアイデア
* * *
cl1pに投稿するデータ(transfer.shのURL)を暗号化する時、
単純にTTCP_PASSWORDを使って暗号化するのはあまり意味がない。
総当りでcl1pにあるデータを探られ、パスワードがバレたら、
そのままtransfer.shにあるデータも復号化されるので。

それから、今はcl1pの管理者側にユーザのIDがバレてる状態なのもあまりよくない。
joeアカウントの場合、すぐに筒抜けになってしまうので。
そこで、下記の4種類の変数を用意し、ユーザが適当に設定してもそこそこのセキュリティ強度を保てるようにしたい。

```
cl1p.net用のID -- cl1p.netのURLに指定するID
cl1p.net用のPASSWORD -- cl1p.netに投稿する文字列の暗号化用パスワード
transfer.sh用のID -- transfer.shのURLに指定するID
transfer.sh用のPASSWORD -- データの暗号化用パスワード
```

上記4種類の変数は、全て別々である必要がある。
とはいえ、4種類の変数をユーザに指定させるのも手間なので、下記の手法を提案する。
まず4種類(ユーザが指定するのは今まで通り2種類、2つsaltを我々で用意)の変数を用意する。

```
TTCP_ID
TTCP_PASSWORD
TTCP_SALT1
TTCP_SALT2
```

この4種類の変数と、ハッシュ関数(sha512)を組み合わせて、4種類のID/PASSを作る。
+記号は文字列の連結。こんな感じ？。

```
* cl1p.net用のID = sha512(TTCP_ID + TTCP_SALT1)
* cl1p.net用のPASSWORD = sha512(TTCP_PASSWORD + TTCP_SALT1)
* transfer.sh用のID = sha512(TTCP_ID + TTCP_SALT2)
* transfer.sh用のPASSWORD = sha512(TTCP_PASSWORD + TTCP_ID + TTCP_SALT2)
```

数字と英語小文字だけとはいえsha512の結果は128文字もあるので、コンテンツのパスワードはsha512の結果をパスワードにする。

1文字などのパスワードをユーザが指定したとしても、sha512さんがそこそこ強いパスワードにしてくれるので。httpの経路で誰かに盗聴されても大丈夫。（もちろんその盗聴する人がttcopyのアルゴリズムを知ってたらダメだけど）。

cl1p.netの管理者が情報を盗聴しようとする場合、まずtransfer.shのURLを手に入れる必要がある。
2つの方法があり、一つは総当たりで投稿された文字列の復号化を試すこと。
これは時間をかければできるかもしれないが、パスワードが十分複雑なら14日はかかるでしょうという前提。

もう一つは、cl1p.netの管理者とtransfer.shの管理者で結託する方法。
しかしこれも、両者のURLのSALTが異なるため、ID(URLのファイル名)によるマッチングはできない。

最後に、transfer.shの管理者が悪さをしようとする場合。これはもうどうしようもない。
ただせめて、transfer.shにアップロードされるコンテンツの復号化には、IDとパスワード両方が必要な状態にする（`transfer.sh用のPASSWORD`）。最悪のケース、いずれかの管理者が誰かのパスワードを当てたとしても、IDも必要なので、計算量大きくて諦めるのではという話。

**Comment by greymd** [comment]
hmm. This way may have weak point... excuse me.

**Comment by mecab** [comment]
SALT作ってハッシュするの、ユーザ的には利便性悪くないし（さらに、気にする人はSALT変えればいいし）、めっちゃ良い気がします！ぜひこれで！

**Comment by greymd** [comment]
sha512じゃなくてsha256使います。理由としては、暗号化方式がAES-256-CBCで、暗号化に使う鍵の長さは256bit固定らしいので、長くしてもあんま意味がないからです。
（いままでopensslが可変長のパスワードを使って暗号化してくれていたのは、内部でハッシュ関数を使って256bitに合わせていたから、だと思う。たぶん。きっと。）

**Comment by mecab** [comment]
Fixed by #34
