### ISSUE TITLE
Load ID and password from ~/.ttcopy if the env is not set

### ISSUE THREAD

**Issue by mecab** [greymd/ttcopy#5]
And generate it automatically at the first run.

It is good starting up.

**Comment by greymd** [comment]
like this

```
TTCP_ID=bbb
TTCP_PASSWORD=aaa
```

**Comment by mecab** [comment]
`-i` and `-p` is enough at this time.
If someone wants to work, please raise PR.

**Comment by greymd** [comment]
My idea

```sh
# In case of first run.
$ echo "AAA" | ttcopy
Set default ID/Password.
ID: # <= Filling in it.
Password: # <= Filling in it.

If you hope to show this screen again,
please execute `ttcopy --init`

# => And credential information is stored to ~/.ttcopy/config with 400 permission.
```

Priority
* 1: `-i` and `-p` options
* 2: TTCP_ID/TTCP_PASSWORD env variables (For management use. I want to hide this feature to users as much as possible.)
* 3: `~/.ttcopy/config`

1 is most prioritized.

**Comment by mecab** [comment]
Yes, showing the prompt is friendly. && I agree to the priority.

**Comment by greymd** [comment]
Working on with `feature/credential_init`.

**Comment by mecab** [comment]
Hero!
